<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerB4b1QSE\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerB4b1QSE/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerB4b1QSE.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerB4b1QSE\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerB4b1QSE\App_KernelDevDebugContainer([
    'container.build_hash' => 'B4b1QSE',
    'container.build_id' => '2a850ef2',
    'container.build_time' => 1612342537,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerB4b1QSE');
